import type { Metadata } from "next";
import "./globals.css";
import { ProductProvider } from "@/context/ProductContext";
import {Header} from "@/components/Header";
import { OrderProvider } from "@/context/OrderContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProductProvider>
          <OrderProvider>
            <Header />
            {children}
          </OrderProvider>
        </ProductProvider>
      </body>
    </html>
  );
}
