import type { Metadata } from "next";
import "./globals.css";
import { ProductProvider } from "@/context/ProductContext";
import { Header } from "@/components/Header";
import { OrderProvider } from "@/context/OrderContext";
import { UserProvider } from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <ProductProvider>
            <OrderProvider>
              <Header />
              {children}
            </OrderProvider>
          </ProductProvider>
        </UserProvider>
      </body>
    </html>
  );
}
